"""File tool protocol scaffolding and workspace-only path policy helpers."""

from .errors import FILE_TOOL_ERROR_CODES, FileToolError, FileToolErrorCode
from .glob_search import FileToolGlobSearcher, GlobSearchPayload
from .grep_search import FileToolGrepSearcher, GrepSearchPayload
from .path_policy import (
    FileToolPathPolicy,
    PathResolution,
    RootPolicy,
    SymlinkPolicy,
    ensure_within_workspace,
    is_hidden_path,
)
from .protocol import (
    AuditMetadata,
    FileToolCallMetadata,
    GlobMatch,
    GlobRequest,
    GrepMatch,
    GrepRequest,
    PathKind,
    PathMetadata,
    ReadRequest,
    ReadResult,
    ToolName,
    ToolResultEnvelope,
)
from .runtime_bindings import (
    FILE_TOOL_GLOB_FUNCTION_NAME,
    FILE_TOOL_GLOB_ID,
    FILE_TOOL_GREP_FUNCTION_NAME,
    FILE_TOOL_GREP_ID,
    FILE_TOOL_READ_FUNCTION_NAME,
    FILE_TOOL_READ_ID,
    RuntimeFileToolGlobContract,
    RuntimeFileToolGrepContract,
    RuntimeFileToolReadContract,
    build_file_tool_glob_runtime_binding,
    build_file_tool_grep_runtime_binding,
    build_file_tool_read_runtime_binding,
)
from .service import FileToolGlobService, FileToolGrepService, FileToolReadService
from .text_reader import FileToolTextReader, TextReadPayload

__all__ = [
    "AuditMetadata",
    "FILE_TOOL_ERROR_CODES",
    "FILE_TOOL_GLOB_FUNCTION_NAME",
    "FILE_TOOL_GLOB_ID",
    "FILE_TOOL_GREP_FUNCTION_NAME",
    "FILE_TOOL_GREP_ID",
    "FILE_TOOL_READ_FUNCTION_NAME",
    "FILE_TOOL_READ_ID",
    "FileToolCallMetadata",
    "FileToolError",
    "FileToolErrorCode",
    "FileToolGlobSearcher",
    "FileToolGlobService",
    "FileToolGrepSearcher",
    "FileToolGrepService",
    "FileToolPathPolicy",
    "FileToolReadService",
    "FileToolTextReader",
    "GlobMatch",
    "GlobRequest",
    "GlobSearchPayload",
    "GrepMatch",
    "GrepRequest",
    "GrepSearchPayload",
    "PathKind",
    "PathMetadata",
    "PathResolution",
    "ReadRequest",
    "ReadResult",
    "RootPolicy",
    "RuntimeFileToolGlobContract",
    "RuntimeFileToolGrepContract",
    "RuntimeFileToolReadContract",
    "SymlinkPolicy",
    "TextReadPayload",
    "ToolName",
    "ToolResultEnvelope",
    "build_file_tool_glob_runtime_binding",
    "build_file_tool_grep_runtime_binding",
    "build_file_tool_read_runtime_binding",
    "ensure_within_workspace",
    "is_hidden_path",
]
