export const DEFAULT_RUNTIME_HOST = '127.0.0.1'
export const DEFAULT_RUNTIME_APP_MODE = 'desktop'
export const DEFAULT_RUNTIME_ENVIRONMENT = 'development'
export const DEFAULT_STARTUP_TIMEOUT_MS = 30_000
export const DEFAULT_SHUTDOWN_TIMEOUT_MS = 5_000
export const DEFAULT_HEALTHCHECK_INTERVAL_MS = 300
export const DEFAULT_HEALTHCHECK_REQUEST_TIMEOUT_MS = 1_500

export const DESKTOP_RUNTIME_ENV_NAMES = {
  HOST: 'COPILOT_DESKTOP_RUNTIME_HOST',
  PORT: 'COPILOT_DESKTOP_RUNTIME_PORT',
  LOCAL_TOKEN: 'COPILOT_DESKTOP_RUNTIME_LOCAL_TOKEN',
  USER_DATA_DIR: 'COPILOT_DESKTOP_RUNTIME_USER_DATA_DIR',
  ROOT_DIR: 'COPILOT_DESKTOP_RUNTIME_ROOT_DIR',
  CONFIG_DIR: 'COPILOT_DESKTOP_RUNTIME_CONFIG_DIR',
  LOGS_DIR: 'COPILOT_DESKTOP_RUNTIME_LOGS_DIR',
  DATABASE_DIR: 'COPILOT_DESKTOP_RUNTIME_DATABASE_DIR',
  STATE_DIR: 'COPILOT_DESKTOP_RUNTIME_STATE_DIR',
  COPILOT_SETTINGS_FILE: 'COPILOT_DESKTOP_RUNTIME_SETTINGS_FILE',
  HOST_LOG_FILE: 'COPILOT_DESKTOP_RUNTIME_HOST_LOG_FILE',
  BACKEND_STDOUT_LOG_FILE: 'COPILOT_DESKTOP_RUNTIME_BACKEND_STDOUT_LOG_FILE',
  BACKEND_STDERR_LOG_FILE: 'COPILOT_DESKTOP_RUNTIME_BACKEND_STDERR_LOG_FILE',
  RUNTIME_SNAPSHOT_FILE: 'COPILOT_DESKTOP_RUNTIME_SNAPSHOT_FILE',
  LAST_FAILURE_FILE: 'COPILOT_DESKTOP_RUNTIME_LAST_FAILURE_FILE',
  APP_MODE: 'COPILOT_DESKTOP_RUNTIME_APP_MODE',
  ENVIRONMENT: 'COPILOT_DESKTOP_RUNTIME_ENVIRONMENT',
} as const

export const HOSTED_RUNTIME_OVERRIDE_ENV_NAMES = {
  HOST: DESKTOP_RUNTIME_ENV_NAMES.HOST,
  ENVIRONMENT: DESKTOP_RUNTIME_ENV_NAMES.ENVIRONMENT,
  STARTUP_TIMEOUT_MS: 'COPILOT_DESKTOP_RUNTIME_STARTUP_TIMEOUT_MS',
  SHUTDOWN_TIMEOUT_MS: 'COPILOT_DESKTOP_RUNTIME_SHUTDOWN_TIMEOUT_MS',
  HEALTHCHECK_INTERVAL_MS: 'COPILOT_DESKTOP_RUNTIME_HEALTHCHECK_INTERVAL_MS',
  HEALTHCHECK_REQUEST_TIMEOUT_MS: 'COPILOT_DESKTOP_RUNTIME_HEALTHCHECK_REQUEST_TIMEOUT_MS',
} as const

export const HOSTED_RUNTIME_MODEL_ENV_NAMES = {
  PRIMARY: 'COPILOT_RUNTIME_MODEL',
  LEGACY: 'COPILOT_MODEL',
} as const

export const HOSTED_RUNTIME_MAIN_PROCESS_ARGUMENT_NAMES = {
  MODEL: '--runtime-model',
  HOST: '--runtime-host',
  APP_MODE: '--runtime-app-mode',
  ENVIRONMENT: '--runtime-environment',
  LOCAL_TOKEN: '--runtime-local-token',
} as const

export const HOSTED_RUNTIME_MAIN_PROCESS_ARGUMENT_FLAGS = new Set<string>(
  Object.values(HOSTED_RUNTIME_MAIN_PROCESS_ARGUMENT_NAMES),
)

export const DESKTOP_RUNTIME_ARGUMENT_NAMES = {
  HOST: '--host',
  PORT: '--port',
  APP_MODE: '--app-mode',
  ENVIRONMENT: '--environment',
  ROOT_DIR: '--root-dir',
  USER_DATA_DIR: '--user-data-dir',
  CONFIG_DIR: '--config-dir',
  LOGS_DIR: '--logs-dir',
  DATABASE_DIR: '--database-dir',
  STATE_DIR: '--state-dir',
  SETTINGS_FILE: '--settings-file',
  HOST_LOG_FILE: '--host-log-file',
  BACKEND_STDOUT_LOG_FILE: '--backend-stdout-log-file',
  BACKEND_STDERR_LOG_FILE: '--backend-stderr-log-file',
  RUNTIME_SNAPSHOT_FILE: '--runtime-snapshot-file',
  LAST_FAILURE_FILE: '--last-failure-file',
  HOST_MODEL_ROUTE_BRIDGE_URL: '--host-model-route-bridge-url',
  HOST_MODEL_ROUTE_BRIDGE_TOKEN: '--host-model-route-bridge-token',
  MODEL: '--model',
  LOCAL_TOKEN: '--local-token',
} as const

export const HOSTED_RUNTIME_CHILD_ENV_NAMES_TO_STRIP = [
  ...Object.values(DESKTOP_RUNTIME_ENV_NAMES),
  ...Object.values(HOSTED_RUNTIME_MODEL_ENV_NAMES),
]
