"""Public surface for the minimal Copilot runtime run bridge."""

from .agent import (
    AgentExecutionError,
    DEFAULT_AGENT_NAME,
    DEFAULT_AGENT_SYSTEM_PROMPT,
    ModelNotConfiguredError,
    PydanticAIAgentExecutor,
)
from .agent_registry import AgentDescriptor, AgentRegistry, build_default_agent_registry
from .bridge import (
    RuntimeBridge,
    RunNotFoundError,
    SessionNotFoundError,
    ThreadNotFoundError,
)
from .composition import RuntimeDependencies, build_default_runtime_dependencies
from .contracts import (
    AGENTS_LIST_METHOD,
    CAPABILITIES_GET_METHOD,
    GLOBAL_TOOL_CATALOG_GET_METHOD,
    RUN_CANCEL_METHOD,
    RUN_START_METHOD,
    RUN_STREAM_METHOD,
    THREAD_CREATE_METHOD,
    THREAD_GET_METHOD,
    TOOL_APPROVAL_RESOLVE_METHOD,
    RuntimeCapabilitiesGetRequest,
    RuntimeCapabilitiesResponse,
    RuntimeMessageExecutionPolicy,
    RuntimeMessagePayload,
    RuntimeToolPermissionPolicy,
    RuntimeRunCancelRequest,
    RuntimeRunCancelResponse,
    RuntimeRunStartRequest,
    RuntimeToolApprovalResolveRequest,
    RuntimeToolApprovalResolveResponse,
    RuntimeRunStartResponse,
    RuntimeRunStreamRequest,
    RuntimeRunView,
    RuntimeScaffold,
    RuntimeThreadCreateRequest,
    RuntimeThreadCreateResponse,
    RuntimeThreadGetRequest,
    RuntimeThreadGetResponse,
    RuntimeToolDirectoryEntry,
    build_runtime_scaffold,
)
from .persistence import SQLiteSessionStore
from .router import build_router
from .runtime_session_store import RuntimeSessionStore
from .tool_approval_coordinator import (
    RuntimeToolApprovalCoordinator,
    RuntimeToolApprovalRequest,
    RuntimeToolApprovalResolution,
    ToolApprovalConflictError,
    ToolApprovalNotFoundError,
)
from .tool_permissions import RuntimeToolPermissionResolver, parse_tool_timeout_seconds
from .tool_registry import (
    ToolDescriptor,
    ToolRegistry,
    ToolsetDescriptor,
    build_default_tool_registry,
    normalize_tool_catalog_language,
)

__all__ = [
    "AGENTS_LIST_METHOD",
    "CAPABILITIES_GET_METHOD",
    "GLOBAL_TOOL_CATALOG_GET_METHOD",
    "RUN_CANCEL_METHOD",
    "RUN_START_METHOD",
    "RUN_STREAM_METHOD",
    "THREAD_CREATE_METHOD",
    "THREAD_GET_METHOD",
    "TOOL_APPROVAL_RESOLVE_METHOD",
    "AgentDescriptor",
    "AgentExecutionError",
    "AgentRegistry",
    "DEFAULT_AGENT_NAME",
    "DEFAULT_AGENT_SYSTEM_PROMPT",
    "ModelNotConfiguredError",
    "PydanticAIAgentExecutor",
    "RunNotFoundError",
    "RuntimeBridge",
    "RuntimeCapabilitiesGetRequest",
    "RuntimeCapabilitiesResponse",
    "RuntimeDependencies",
    "RuntimeMessageExecutionPolicy",
    "RuntimeMessagePayload",
    "RuntimeRunCancelRequest",
    "RuntimeToolApprovalResolveRequest",
    "RuntimeToolApprovalResolveResponse",
    "RuntimeToolPermissionPolicy",
    "RuntimeRunCancelResponse",
    "RuntimeRunStartRequest",
    "RuntimeRunStartResponse",
    "RuntimeRunStreamRequest",
    "RuntimeRunView",
    "RuntimeScaffold",
    "RuntimeThreadCreateRequest",
    "RuntimeThreadCreateResponse",
    "RuntimeThreadGetRequest",
    "RuntimeThreadGetResponse",
    "RuntimeToolDirectoryEntry",
    "SessionNotFoundError",
    "ThreadNotFoundError",
    "SQLiteSessionStore",
    "RuntimeSessionStore",
    "ToolDescriptor",
    "ToolRegistry",
    "ToolsetDescriptor",
    "normalize_tool_catalog_language",
    "RuntimeToolApprovalCoordinator",
    "RuntimeToolApprovalRequest",
    "RuntimeToolApprovalResolution",
    "RuntimeToolPermissionResolver",
    "ToolApprovalConflictError",
    "ToolApprovalNotFoundError",
    "parse_tool_timeout_seconds",
    "build_default_agent_registry",
    "build_default_runtime_dependencies",
    "build_default_tool_registry",
    "build_router",
    "build_runtime_scaffold",
]
